default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Snapshots")
  end

  lane :beta do
    sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app(scheme: "iOS App")
    upload_to_testflight
  end

  lane :release do
    build_app(scheme: "iOS App")
  end
end
